
import { NavbarDefault } from '@/components/shared/nabbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/shared/navbar'
import RootWrapper from '@/components/views/RootWrapper'
import { Providers } from '@/redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <Providers>
      <body className={inter.className}>
      <Navbar/> 
      <RootWrapper>
        {children}
        </RootWrapper>
        </body>
        </Providers>
    </html>
  )
}
